language: python
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
install:
    - sudo apt-get -y update
    - sudo apt-get -y install r-base
    - pip install codecov
    - pip install -r requirements.txt
    - cd hotnet2
    - python hotnet2/setup_fortran.py build_src build_ext --inplace
    - python hotnet2/setup_c.py build_src build_ext --inplace
    - cd ..
script:
    - nosetests
after_success:
    - codecov
